lostzen/lost

lost-sample/src/main/java/com/example/lost/LostActivity.java, lost-sample/src/main/res/layout/list_item.xml, lost/build.gradle, lost/src/main/java/com/mapzen/android/lost/internal/MockEngine.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/MockEngineTest.java
Adds bearing to mock locations emitted by GPX replay. Uses previous and current coordinates to calculate approximate value.
Testing this feature enabled by Robolectric upgrade to fix thread scheduler problem that was causing mock locations to be delivered in reverse order when posted to main thread handler.
Updates sample app to display bearing value.
Closes #36
=> Mock location bearing

lost/build.gradle
Changes minimum SDK from 21 to 15 in library and sample app to allow LOST to be included in projects that target older versions of Android.
Tested both LOST Sample and EraserMap on Galaxy S2 running Android 4.0.4 and encountered no issues.
=> Minimum SDK 15

circle.yml, lost-sample/build.gradle, lost/build.gradle
Depends on #42 since the library snapshot must be deployed before sample app can successfully build.
=> Update minimum SDK in sample app

lost-sample/src/main/AndroidManifest.xml, lost/src/main/AndroidManifest.xml
Library permissions are now only `ACCESS_COARSE_LOCATION` and `ACCESS_FINE_LOCATION`.
Sample application adds `READ_EXTERNAL_STORAGE` to allow mock GPX trace replay from SD card.
=> Remove extra manifest permissions

lost-sample/build.gradle, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java, lost/src/main/java/com/mapzen/android/lost/internal/LocationEngine.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/MockEngine.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusionEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/MockEngineTest.java
* Creates new `LocationEngine` per `LocationRequest`
* Adds/removes listeners for given `LocationEngine`
* Shuts `LocationEngine` down when no listeners exist for it
* Requires removal of all listeners before calling `LostApiClient#disconnect()` to properly shutdown client
Closes #47
=> Support multiple listeners in FusedLocationApi

lost/src/main/java/com/mapzen/android/lost/api/LostApiClient.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java
- Instead of shutting down all engines when mock mode is toggled on/off, toggle them so that `MockEngine`s are created for existing listeners when mock mode enabled
- Add method to get the number of listeners so that shared instances of `LostApiClient` can know whether or not they should call `disconnect`
=> Dont remove listeners on setMockMode

lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java, lost/src/main/java/com/mapzen/android/lost/internal/LocationEngine.java, lost/src/main/java/com/mapzen/android/lost/internal/LocationRequestUnbundled.java, lost/src/main/java/com/mapzen/android/lost/internal/MockEngine.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusionEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/MockEngineTest.java
- Use single `LocationEngine` in `FusedLocationProviderApiImpl`
- Bundle `LocationRequest` into `LocationRequestUnbundled`
As a result of these changes, listeners may receive results that are more/less accurate than requested but I think this is okay given that the LocationRequest documentation says this:
"All location requests are considered hints, and you may receive locations that are more/less accurate, and faster/slower than requested."
https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest
Closes #57
=> Enforce 1-1 request/listener relationship

lost-sample/src/main/AndroidManifest.xml, lost/src/main/AndroidManifest.xml, lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java, lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java
Permissions `ACCESS_COARSE_LOCATION` and `ACCESS_FINE_LOCATION` should not be included in the LOST library `AndroidManifest.xml`. Instead they should be added as required by client applications based on their API use and additionally requested at runtime on API 23+.
Location permissions have been removed from the library manifest and added to the sample application. `FusedLocationProviderApi` has been modified to use support annotations for `@RequiresPermission`. Finally `throws SecurityException` has been explicitly added to all `FusionEngine` methods that may be rejected if permissions have not been granted by the user.
Closes #75
=> Remove location permissions

lost-sample/src/main/java/com/example/lost/FusedLocationApiActivity.java, lost/src/main/AndroidManifest.xml, lost/src/main/java/com/mapzen/android/lost/api/LostApiClient.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderService.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/MockEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestLocationListener.java
This PR creates a service for the `FusedLocationProviderApi` to run in. When clients connect, the service will be started if it isn't already running. When clients disconnect, the service will ~~remain running (until the system kills it)~~ be shutdown.
These changes move the `FusedLocationProviderApiImpl` code into a class called `FusedLocationProviderServiceImpl` which is instantiated and invoked inside of the new `FusedLocationProviderService`. With this change, we now have a new interface, `ConnectionCallbacks`, which client applications should use to know when they can start interacting with the `FusedLocationApi`, etc APIs.
Closes #63
=> 63 background service

lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java, lost/src/main/java/com/mapzen/android/lost/api/LocationAvailability.java, lost/src/main/java/com/mapzen/android/lost/api/LocationCallback.java, lost/src/main/java/com/mapzen/android/lost/api/LocationResult.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderService.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestLocationCallback.java, lost/src/test/java/com/mapzen/android/lost/internal/TestLocationListener.java
This PR adds the ability to query for `LocationAvailability` as well as the ability to request location updates for a given `LocationCallback`. It also makes `PendingIntent`s more complete with information and adds extras `EXTRA_LOCATION_AVAILABILITY` and `EXTRA_LOCATION_RESULT` to be delivered with each `Intent`.
The `FusedLocationProviderApi` api has three new methods (`getLocationAvailability()`, `requestLocationUpdates(LocationRequest request, LocationCallback callback, Looper looper)`, and `removeLocationUpdates(LocationCallback callback)`). This PR also adds a new `Parcelable` class `LocationAvailability` as well as a new interface, `LocationCallback`.
Closes #64
=> 64 location availability

lost-sample/src/main/AndroidManifest.xml, lost-sample/src/main/java/com/example/lost/GeofenceIntentService.java, lost-sample/src/main/java/com/example/lost/GeofencingApiActivity.java, lost-sample/src/main/java/com/example/lost/SamplesList.java, lost-sample/src/main/res/layout/activity_geofencing.xml, lost-sample/src/main/res/values/strings.xml, lost/src/main/java/com/mapzen/android/lost/api/Geofence.java, lost/src/main/java/com/mapzen/android/lost/api/GeofencingApi.java, lost/src/main/java/com/mapzen/android/lost/api/GeofencingRequest.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/ParcelableGeofence.java, lost/src/test/java/com/mapzen/android/lost/api/GeofenceTest.java, lost/src/test/java/com/mapzen/android/lost/api/GeofencingRequestTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingApiTest.java, lost/src/test/java/com/mapzen/android/lost/internal/MockEngineTest.java
This pull request adds basic geofence support. The scope of initial support is to register a single proximity alert using the `GeofencingRequest` API. Under the hood the geofencing API uses [`LocationManager.addProximityAlert(...)`](https://developer.android.com/reference/android/location/LocationManager.html#addProximityAlert(double, double, float, long, android.app.PendingIntent)) to implement the alerts.
Add implementation for `GeofencingApi.addGeofences(GeofencingRequest geofencingRequest, PendingIntent pendingIntent)` to allow client apps to create a proximity alert and receive a `PendingIntent`  callback when the geofence is entered or exited.
Also a new `Activity` and `IntentService` will be added to the sample application to demonstrate the geofencing API.
* **At this time …
=> Initial geofencing support

lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java, lost/src/main/java/com/mapzen/android/lost/api/Status.java, lost/src/main/java/com/mapzen/android/lost/internal/ClientManager.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationPendingResult.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderService.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostClientManager.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationPendingResultTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestResultCallback.java
This PR updates the return type in several `FusedLocationProviderApi` methods from `void` to `PendingResult`
A `FusedLocationPendingResult` object will be returned for the updated `FusedLocationProviderApi` methods. This is a simple object that always returns a `Status` with code `Status#SUCCESS`. In cases where `FusedLocationProviderApi#removeLocationUpdates` is called without `FusedLocationProviderApi#registerLocationUpdates`, the returned result object will do nothing when `FusedLocationPendingResult#setResultCallback` is invoked.
Scenarios I tested on play services which inspired the design of this include:
-request location when location services disabled -> `Result.Success`
-request location before client connected -> `IllegialStateException` thrown
-request location updates without …
=> PendingResult return type

build.gradle, gradle/wrapper/gradle-wrapper.properties, lost-sample/build.gradle, lost-sample/src/main/java/com/example/lost/FusedLocationApiActivity.java, lost/build.gradle, lost/src/main/java/com/mapzen/android/lost/api/GeofencingEvent.java, lost/src/main/java/com/mapzen/android/lost/api/GeofencingRequest.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/ParcelableGeofence.java, lost/src/test/java/com/mapzen/android/lost/internal/FusionEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingApiTest.java
Rebase of #88, continuing to implement Geofencing support, also the API level bump is reverted
-     bump gradle versions
-     add dcendents dependency
-     implement adding Geofences by List in builder
-     implement adding Geofences by List
-     implement Geofence removal
-     add GeofencingEvent scaffold
=> [WIP] Rebase of continued Geofence implementation (see #86, #88)

.github/CONTRIBUTING.md, build.gradle, config/checkstyle/checkstyle.xml, gradle/wrapper/gradle-wrapper.properties, lost-sample/build.gradle, lost-sample/src/main/java/com/example/lost/FusedLocationApiActivity.java, lost/build.gradle, lost/src/main/java/com/mapzen/android/lost/api/GeofencingEvent.java, lost/src/main/java/com/mapzen/android/lost/api/GeofencingRequest.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/ParcelableGeofence.java, lost/src/test/java/com/mapzen/android/lost/internal/FusionEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingApiTest.java
Hi, I wanted to use Checkstyle directly from within the Android Studio GUI, so hints can be displayed while coding, I thought that might make it easier to adhere to the style.
The current plugin (https://plugins.jetbrains.com/plugin/1065, 4.31.0, 2016-08-06) comes with Checkstyle 7.1/31 Jul 2016, but the rule `RedundantThrows`, used in `config/checkstyle/checkstyle.xml`
is not being supported any more by Checkstyle since v. 6.2/28 Dec 2014 (because it is said to be an "Example of really buggy Check", see https://github.com/checkstyle/checkstyle/issues/473#issuecomment-91093541 and http://checkstyle.sourceforge.net/releasenotes.html#Release_6.2).
I tried using an outdated version of the plugin (4.14.3, 2015-03-14, https://plugins.jetbrains.com/update/index?pr=&updateId=18978) with the old …
=> Change checkstyle rules to allow for current version

circle.yml, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java
Fixes failing build on Circle CI by adding `android-24`, `build-tools-24.0.1` , and `oraclejdk8` to build config and fixing checkstyle errors.
* Adds `android-24` and `build-tools-24.0.1` to Circle CI dependencies.
* Configures the Circle CI build machine to use `oraclejdk8` as Java 8 is required for Android 24.
* Fixes checkstyle (line >100 characters) errors by adding static imports for manifest permissions.
=> Adds "android-24" to Circle CI dependencies

config/checkstyle/suppressions.xml, lost/src/main/java/com/mapzen/android/lost/api/LocationServices.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/SettingsApiImpl.java, lost/src/test/java/com/mapzen/android/lost/api/LocationServicesTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingApiTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java
This PR prevents the static APIs from being able to be modified by clients.
- Make `LocationServices` fields final
- Add `connect()`, `isConnected()`, and `disconnect()` methods for all APIs
- Update `LostApiClientImpl` to use new `connect()`, `isConnected()`, and `disconnect()` methods for corresponding methods
- Update and add tests
Closes #33
=> Make LocationServices fields final

lost/src/main/java/com/mapzen/android/lost/api/GeofencingApi.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/SimplePendingResult.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingApiTest.java, lost/src/test/java/com/mapzen/android/lost/internal/SimplePendingResultTest.java
Adds `PendingResult` to `GeofencingApi`
- Returns `PendingResult` object for all API calls to `GeofencingApi`
- Refactors `FusedLocationPendingResult` to `SimplePendingResult` to be shared by `FusedLocationProviderApi` and `GeofencingApi`
Closes #99
=> Add PendingResult to GeofencingApi

circle.yml, lost-sample/build.gradle, lost/build.gradle
Update Android build tools and support libs to latest versions.
* Build tools version 24.0.2
* Support annotations and appcompat version 24.2.1
=> Update build tools and support libs

lost/src/main/AndroidManifest.xml, lost/src/main/java/com/mapzen/android/lost/api/GeofencingApi.java, lost/src/main/java/com/mapzen/android/lost/api/GeofencingIntentSender.java, lost/src/main/java/com/mapzen/android/lost/api/GeofencingIntentService.java, lost/src/main/java/com/mapzen/android/lost/api/LocationServices.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingServiceIntentFactory.java, lost/src/main/java/com/mapzen/android/lost/internal/IntentFactory.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingApiTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingIntentSenderTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestIntentFactory.java
This PR adds 3 extras to be sent in the `PendingIntent` fired from calls to `GeofencingApi#addGeofence`
Like a familiar library also does, this change adds extras `EXTRA_TRANSITION `, `EXTRA_GEOFENCE_LIST `, `EXTRA_TRIGGERING_LOCATION ` to all intents fired by the `GeofencingApi`.
Nuances:
- At the moment the EXTRA_TRANSITION, will always be 1 because I only seem to be getting "entering" information from the intent fired by `LocationManager`.
- EXTRA_TRIGGERING_LOCATION is the location returned by `FusionEngine#getLastLocation()`
Closes #100
=> 100 geofencing event extra

build.gradle, lost-sample/build.gradle, lost/build.gradle
Update Gradle script to version 2.2.0
Modifies Gradle version in all `build.gradle` files and adds `jcenter()` repo to root build script.
=> Update Gradle to version 2.2.0

lost-sample/src/main/java/com/example/lost/GeofencingApiActivity.java, lost/src/main/AndroidManifest.xml, lost/src/main/java/com/mapzen/android/lost/api/Geofence.java, lost/src/main/java/com/mapzen/android/lost/api/GeofencingIntentSender.java, lost/src/main/java/com/mapzen/android/lost/api/LocationServices.java, lost/src/main/java/com/mapzen/android/lost/internal/DwellIntentService.java, lost/src/main/java/com/mapzen/android/lost/internal/DwellServiceIntentFactory.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofenceIntentHelper.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingDwellManager.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingIntentService.java, lost/src/main/java/com/mapzen/android/lost/internal/ParcelableGeofence.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingApiTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingDwellManagerTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingIntentSenderTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestDwellIntentFactory.java
This PR adds support for setting a loitering delay on `Geofence` as well as dispatching dwell transition events.
When a geofence is entered, an alarm is scheduled to fire after a delay determined by the value of the geofence's loitering delay. When the alarm fires, the dwell transition is sent in the `Intent` data. If a geofence is exited before this interval, then the alarm is cancelled and no dwell transition is fired.
Closes #116
=> 116 dwell transition

circle.yml
Separates installation of Android SDK dependencies on Circle CI.
Fixes license error by accepting each license one at a time.
```
> You have not accepted the license agreements of the following SDK components:
[Android Support Repository].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
```
=> Install SDK dependencies one at a time

docs/mock-locations-routes.md, lost-sample/src/main/java/com/example/lost/LocationListenerActivity.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/GpxTraceThreadFactory.java, lost/src/main/java/com/mapzen/android/lost/internal/LocationRequestUnbundled.java, lost/src/main/java/com/mapzen/android/lost/internal/MockEngine.java, lost/src/main/java/com/mapzen/android/lost/internal/SleepFactory.java, lost/src/main/java/com/mapzen/android/lost/internal/ThreadSleepFactory.java, lost/src/main/java/com/mapzen/android/lost/internal/TraceThread.java, lost/src/main/java/com/mapzen/android/lost/internal/TraceThreadFactory.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/MockEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TraceThreadTest.java, scripts/install-gpx-trace.sh
* Fixes mock trace unit tests that would fail due to concurrency issues.
* Fixes mock routing in sample app.
Refactors mock GPX trace logic so it can be tested synchronously. Cleans up classes and adds interfaces to facilitate testing.
Updates sample app to load a mock GPX trace from its external files directory. Previously the trace file was loaded from the root of the SD card which now fails due to insufficient permissions.
This is cleaner than adding the required permissions for accessing all of external storage and is the now the recommended way for developers to use mock traces in a runtime permissions world.
Also adds `fastestInterval` to sample app location request since this is required for mock trace replay to work correctly (background thread sleeps for `fastestInterval` between …
=> Fix mock trace tests and sample app

lost/src/main/java/com/mapzen/android/lost/internal/LocationSettingsResultRequest.java, lost/src/main/java/com/mapzen/android/lost/internal/SettingsApiImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/LocationSettingsResultRequestTest.java, lost/src/test/java/com/mapzen/android/lost/internal/SettingsApiImplTest.java
Don't require bluetooth permission when using the `SettingsApi`
Check that the bluetooth permission is granted before calling `bluetoothAdapter.isEnabled()`
Closes #121
=> Dont require bluetooth permission

lost/src/main/java/com/mapzen/android/lost/api/LocationServices.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManager.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManagerTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestConnectionCallbacks.java
This PR updates the internal connection state for the `FusedLocationProviderApi` before invoking any callbacks. Previously, callbacks were invoked before the state was updated which caused bugs when client logic in callbacks relied on checking `LostApiClient#isConnected`.
This work extracts non-service related logic from `FusedLocationProviderApiImpl` into a new class, `FusedLocationServiceConnectionManager` and adds test coverage for the new class.
Resolves problem described here: https://github.com/mapzen/android/issues/208
=> Fix connection state

lost/src/main/java/com/mapzen/android/lost/internal/ClientManager.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderService.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManager.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostClientManager.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManagerTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientManagerTest.java
Prevent crash due to attempting to unbind service when not currently bound. Simplify logic to disconnect fused location client and service.
* Combines the responsibilities from `LostClientManager.removeClient(LostApiClient)` and `LostClientManager.disconnect(LostApiClient)` into a single method.
* Actively track whether service is currently bound in `FusedLocationProviderApiImpl` to prevent attempts to unbind when service is not bound. Fixes `IllegalArgumentException`.
* Removes client param to `FusedLocationServiceConnectionManager.disconnect()` since it was only ever called with `null`.
* Removes `FusedLocationProviderService.disconnect(LostApiClient)` since disconnecting the client is now handled by `LostClientManager.removeClient(LostApiClient)` called before disconnecting the …
=> Prevent crash due to attempting to unbind service when not currently bound

lost/src/main/java/com/mapzen/android/lost/internal/ClientManager.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostClientManager.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java
This PR updates how `LostApiClient#isConnected` is determined to consider whether the client is being managed by the `ClientManager`.
This fixes a bug where when multiple clients were connected, the method would report that unbound clients were connected.
Closes #134
=> Better is connected logic for multiple clients

lost/src/main/java/com/mapzen/android/lost/api/LostApiClient.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManager.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManagerTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestClientManager.java, lost/src/test/java/com/mapzen/android/lost/internal/TestConnectionCallbacks.java
This PR fixes bugs that occur when checking `LostApiClient` connection state in callbacks.
This changes `FusedLocationServiceConnectionManager` and `LostApiClientImpl` to update their internal state before invoking external callbacks. It also migrates `LostApiClientImpl` to have its `ClientManager` injected and cleans up related tests.
=> Better callback invocation

lost-sample/src/main/AndroidManifest.xml, lost-sample/src/main/java/com/example/lost/LocationAvailabilityActivity.java, lost-sample/src/main/java/com/example/lost/SamplesList.java, lost-sample/src/main/res/layout/activity_location_availability.xml, lost-sample/src/main/res/values/strings.xml, lost/src/main/java/com/mapzen/android/lost/api/LocationListener.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/shadows/LostShadowLocationManager.java
This PR changes the underlying mechanism that Lost uses to notify of providers enabled/disabled from a `LocationListener` to a `ContentObserver` on the system location provider setting.
`FusionEngine` no longer does anything with its provider changed `LocationListener` methods and instead uses `LocationProviderChangedHandler` to receive notifications of providers enabled & disabled. The `LocationProviderChangedHandler` handles setting up a `ContentObserver` to listen to changes to `Settings.System.LOCATION_PROVIDERS_ALLOWED`.
Closes #123
=> Location provider enabled/disabled

lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManager.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java
This PR fixes a bug which caused `ConnectionCallbacks#onConnected` to be called multiple times when the lifecycle of the `LostApiClient` was tied to the `Activity` lifecycle.
This adds a call to remove the `LostApiClient` `ConnectionCallback` when the client is disconnected, making the management of callbacks symmetrical. Previously, they were only added when the client was connected.
Closes #138
=> Remove connection callbacks when client disconnected

lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java, lost/src/test/java/com/mapzen/android/lost/internal/FusionEngineTest.java
This PR updates the `FusionEngine` to check for a last known location for each enabled location provider and return that location if it exists.
Here is example output from these two test classes used
FusedLocationActivity
```
12-06 15:53:11.558 1765-1765/com.mapzen.googleplayservicestest D/Test: onConnected
12-06 15:53:11.568 1765-1765/com.mapzen.googleplayservicestest D/Test: last known network
12-06 15:53:11.568 1765-1765/com.mapzen.googleplayservicestest D/Test: ch acc:2198.0 lat:40.0173948 lng:-105.3028802 provider:network bearing:0.0 nanos:6514803000000 speed:0.0 time:1481064657644
12-06 15:53:11.568 1765-1765/com.mapzen.googleplayservicestest D/Test: lastKnownLocation
12-06 15:53:11.568 1765-1765/com.mapzen.googleplayservicestest D/Test: ch acc:2198.0 lat:40.0173948 lng:-105.3028802 …
```
=> Report last known location when engine enabled

lost/build.gradle, lost/src/main/java/com/mapzen/android/lost/api/Status.java, lost/src/main/java/com/mapzen/android/lost/internal/DialogDisplayer.java, lost/src/main/java/com/mapzen/android/lost/internal/LocationSettingsResultRequest.java, lost/src/main/java/com/mapzen/android/lost/internal/SettingsDialogDisplayer.java, lost/src/main/java/com/mapzen/android/lost/internal/SettingsDialogFragment.java, lost/src/main/java/com/mapzen/android/lost/internal/SimplePendingResult.java, lost/src/main/res/values/strings.xml, lost/src/test/java/com/mapzen/android/lost/api/LocationSettingsResultTest.java, lost/src/test/java/com/mapzen/android/lost/api/StatusTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestSettingsDialogDisplayer.java
This adds an intermediate step between initiation of a Status' resolution and firing of the device's location activity to give the user a chance to reject changing location settings.
Creates a new class, `SettingsDialogDisplayer` to handle showing an alert to prompt the user to continue to the device's location settings screen.
Closes #140
=> Display alert to optionally fire location settings activity

lost/src/main/java/com/mapzen/android/lost/internal/LostClientManager.java, lost/src/main/java/com/mapzen/android/lost/internal/LostClientWrapper.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientManagerTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientWrapperTest.java
Adds `LocationClientWrapper` class to encapsulate a single `LostApiClient` and all its associated listeners, pending intents, callbacks, and loopers.
This change simplifies the logic in `LostClientManager` for adding and removing listeners and sending location updates.
As a second stage to this refactor we may want to consider migrating some of the logic from `LostClientManager.iterateAndNotify()` into the `ClientWrapper` class.
=> Extracts `LocationClientWrapper` class

lost/src/main/java/com/mapzen/android/lost/api/Status.java, lost/src/main/java/com/mapzen/android/lost/internal/DialogDisplayer.java, lost/src/main/java/com/mapzen/android/lost/internal/SettingsDialogDisplayer.java, lost/src/test/java/com/mapzen/android/lost/internal/TestSettingsDialogDisplayer.java
Allows `Status` objects to be passed between Activities
Closes #154
=> Status implements Parcelable

config/checkstyle/suppressions.xml, lost/build.gradle, lost/src/test/java/com/mapzen/android/lost/api/LocationRequestTest.java, lost/src/test/java/com/mapzen/android/lost/api/LocationServicesTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusionEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingIntentSenderTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java, lost/src/test/java/com/mapzen/android/lost/shadows/LostShadowLocationManager.java
Upgrade Robolectric from version 3.1.2 to version 3.2.1 (latest).
* Upgrades dependency in `build.gradle`
* Replaces all instances of `RobolectricGradleTestRunner` with `RobolectricTestRunner`.
* Updates implementation for `LostShadowLocationManager`.
* Fixes test `requestLocationUpdates_shouldNotNotifyRemovedPendingIntent()` that was failing due to [new implementation](https://github.com/robolectric/robolectric/commit/eaa6aee762dcc90a45edd39aa7a80ac9b78f1dac) for `ShadowPendingIntent#equals(Object)`. Only one `PendingIntent` was getting added to the `Set` of listeners. This is the correct behavior. Because they mapped to the same `Service` class they should be considered equal. Test has been updated to account for this more accurate implementation by creating `PendingIntent`s mapped to …
=> Upgrades Robolectric to version 3.2.1

lost/src/main/java/com/mapzen/android/lost/api/Status.java, lost/src/test/java/com/mapzen/android/lost/api/StatusTest.java
Adds a constructor to allow creating `Status` objects given only a `statusCode`
This is useful for cases where the status code is `SUCCESS`
=> Add constructor for status with only status code param

build.gradle, lost-sample/build.gradle, lost/build.gradle
Upgrades Android Gradle plugin to version 2.2.3
Replace version 2.2.1 with 2.2.3 in `build.gradle` files.
Also updates Gradle default tasks to run debug tests only. Fixes OOM error on Circle CI.
=> Upgrades Android Gradle plugin to version 2.2.3

build.gradle, circle.yml, lost-sample/build.gradle, lost/build.gradle, scripts/deploy-staging.sh
Configures gradle release plugin and `circle.yml` to deploy AAR to Maven Central directly from Circle CI when a new release tag is pushed to Github.
* Adds gradle-release plugin to library `build.gradle`.
* Adds `release` deployment section to `circle.yml`.
* Adds `deploy-staging.sh` script to build, sign, and upload release artifact.
=> Configure release plugin

build.gradle, circle.yml, gradle.properties, lost/src/test/java/com/mapzen/android/lost/BaseRobolectricTest.java, lost/src/test/java/com/mapzen/android/lost/api/LocationRequestTest.java, lost/src/test/java/com/mapzen/android/lost/api/LocationResultTest.java, lost/src/test/java/com/mapzen/android/lost/api/LocationServicesTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusionEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingIntentSenderTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientManagerTest.java, lost/src/test/java/com/mapzen/android/lost/internal/MockEngineTest.java, lost/src/test/java/com/mapzen/android/lost/internal/SystemClockTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TraceThreadTest.java
Caches build tools, platform, and android m2 repo folders on Circle CI. Implment build and test  optimizations.
Adds logic to `circle.yml` to download Android SDK components only if the folder is not already cached. Also specifies which directories should be cached and restored at the beginning of each build.
Lost build on Circle CI has been reduced from ~9 minutes to less than 5 minutes by taking the following measures:
* Cache Android SDK components
* Removing `--refresh-dependencies` from build commands
* [Disabling pre dex](http://www.littlerobots.nl/blog/disable-android-pre-dexing-on-ci-builds/) on Circle CI builds
* Adds BaseRobolectric test to [clean up global window manager memory leaks and shutdown background threads](https://github.com/robolectric/robolectric/issues/2068).
=> Build performance improvements

lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManager.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationServiceConnectionManagerTest.java
Fixes `ConcurrentModificationException` when multiple clients exist and one client is disconnected on connect.
Iterates a over copy of the connection callbacks set stored in the `FusedLocationServiceConnectionManager` when the fused location service is either connected or suspended. This prevent a `ConcurrentModificationException` if callbacks are removed during iteration.
Fixes #162
=> Fixes ConcurrentModificationException when client is disconnected on connect

gradle.properties, lost-sample/src/main/java/com/example/lost/MultipleLocationListenerMultipleClientsActivity.java, lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java
`FusedLocationProviderApi` should throw an exception if the client instance passed into any of its methods is not currently connected.
Updates methods, tests, and documentation to throw an `IllegalStateException` if the `LostApiClient` used is not connected.
Also fixes a crash when exiting the multiple client demo activity due to removing location updates after the fragment client has been disconnected.
Fixes #166
=> Verify client is connected

lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java
Store all connection callbacks in service manager even if the service is already connected.
In `LostApiClientImpl.connect()` all connection callbacks should be added to the `FusedLocationApiImpl` even if the `isConnected()` returns true.
This ensures if the service is later suspended and re-connected the appropriate callbacks will be invoked for all instances of `LostApiClient`.
Fixes #164
=> Store all connection callbacks in the service manager

lost/src/main/AndroidManifest.xml
GPS sensor should not be required to use Lost.
Updates `AndroidManifest.xml` to set `required=false` for `android.hardware.location.gps` feature.
Closes #169
=> GPS feature should not be required to use Lost

lost-sample/src/main/java/com/example/lost/MultipleLocationListenerSingleClientActivity.java, lost/src/main/java/com/mapzen/android/lost/internal/ClientManager.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderService.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostClientManager.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientManagerTest.java
Simplifies service shutdown process to prevent race condition that leads to a crash when the device is rotated.
Removes `FusedLocationProviderServiceImpl#shutdown()`. This method was previously invoked when the system called `FusedLocationProviderService#onDestroy()` and did two things:
1. Clear all location requests by calling `LocationEngine#setRequest(null)`.
2. Clear all location clients from the client manager by calling `LostClientManager#shutdown()`.
The problem is that `FusedLocationProviderService#onDestroy()` would be invoked asynchronously by the system after rotating the device. By the time `onDestroy()` fires the client application may have already re-connected the location client and/or made a new request for location updates.
If `onDestroy()` fires sometime between …
=> Simplify service shutdown to prevent crash on screen rotation

lost-sample/src/main/java/com/example/lost/LocationListenerActivity.java, lost-sample/src/main/java/com/example/lost/MultipleLocationListenerMultipleClientsActivity.java, lost-sample/src/main/java/com/example/lost/MultipleLocationListenerSingleClientActivity.java, lost/src/main/java/com/mapzen/android/lost/api/LocationListener.java, lost/src/main/java/com/mapzen/android/lost/internal/ClientManager.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostClientManager.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientManagerTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestLocationListener.java
Removes deprecated location listener callbacks for provider enabled/disabled.
* Removes deprecated callbacks `LocationListener#onProviderEnabled(String)` and LocationListener#onProviderDisabled(String). Use `LocationAvailability` instead.
* Speeds up location updates in multiple location client demo for faster testing.
This is the first chunk of cleanup work for changes needed to fix #173.
=> Removes deprecated location listener callbacks for provider enabled/disabled

lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderService.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceDelegate.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceDelegateTest.java
Makes all methods in `FusedLocationProviderService` except `getLastLocation()` and `getLocationAvailability()` return `void`.
`FusedLocationProviderApi` methods that return a `PendingResult` now generate the return value in the client-side API implementation rather than in the service.
=> Migrate PendingResult return values from FusedLocationProviderService to FusedLocationProviderApiImpl

lost-sample/src/main/AndroidManifest.xml, lost-sample/src/main/java/com/example/lost/LocationListenerActivity.java, lost-sample/src/main/java/com/example/lost/PendingIntentActivity.java, lost/src/main/AndroidManifest.xml, lost/src/main/aidl/com/mapzen/android/lost/api/LocationAvailability.aidl, lost/src/main/aidl/com/mapzen/android/lost/api/LocationRequest.aidl, lost/src/main/aidl/com/mapzen/android/lost/internal/IFusedLocationProviderCallback.aidl, lost/src/main/aidl/com/mapzen/android/lost/internal/IFusedLocationProviderService.aidl, lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderService.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceDelegate.java, lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java, lost/src/main/java/com/mapzen/android/lost/internal/LocationEngine.java, lost/src/main/java/com/mapzen/android/lost/internal/LostClientManager.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceDelegateTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostApiClientImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientManagerTest.java
Adds multiple process support for Lost fused location provider service.
* Modifies `FusedLocationProviderService` to run in its own process.
* Adds AIDL interface `FusedLocationProviderService`.
* Replaces `FusedLocationProviderBinder` with `IFusedLocationProviderService.Stub`.
* Changes `setMockTrace(File)` to `setMockTrace(String, String)` so they can be passed over IPC.
* Use service's looper when registering as a location listener with `LocationManager`. This also may resolve the issue originally reported here https://github.com/mapzen/lost/issues/131.
* Delivers location updates via `IFusedLocationProviderCallback` AIDL interface and notifies `LostClientManager` on UI thread.
* Moves logic for tracking reported changes from service to …
=> Multiple process support

lost-sample/src/main/java/com/example/lost/PendingIntentActivity.java
- Adds corresponding call to remove updates requested in `requestLocationUpdates` which fixes crash in `PendingIntent` example
Closes #186
=> Fix sample app crash

lost/src/main/java/com/mapzen/android/lost/api/LostApiClient.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceDelegateTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientManagerTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostClientWrapperTest.java
- Migrates `LostApiClient` to use the application context which will exist as long as the hosting process does
- Minor fixes to tests to execute after the Robolectric context is created and to run with Robolectric
Closes #175
=> Fix memory leak

lost/src/main/java/com/mapzen/android/lost/api/GeofencingApi.java, lost/src/main/java/com/mapzen/android/lost/internal/ApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingApiTest.java, lost/src/test/java/com/mapzen/android/lost/internal/GeofencingIntentSenderTest.java
- Updates `GeofencingApi` to throw an `IllegalStateException` if the `LostApiClient` passed in is not connected
- Leaves `SettingsApi` as is to mirror behavior of Play Services which does not throw an exception if the client is not connected
Closes #89
=> Throw IllegalStateException

scripts/deploy-snapshot.sh
Instead of looping through `gradle.properties` to find the version, use the version returned from the`printVersion` task.
=> update snapshot script to use printVersion task

lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/TestServiceStub.java
This PR fixes a race condition that existed when the `LocationEngine` received a location update after the service was disconnected
These changes balance out the connect/disconnect flow from:
`connect -> bind -> register for service callbacks -> unbind -> consider disconnected`
to:
`connect -> bind -> register for service callbacks unregister for service callbacks -> unbind -> consider disconnected`
To reproduce this I created a `BroadcastReceiver` in `LocationEngine` and fired a dummy sample intent to this receiver in `FusedLocationProviderApiImpl#disconnect`
```
05-17 17:37:00.421 23377-23377/com.example.lost E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.lost, PID: 23377
java.lang.NullPointerException: Attempt to invoke interface method …
```
=> Unregister service callbacks on disconnect

lost-sample/src/main/java/com/example/lost/GeofencingApiActivity.java, lost-sample/src/main/java/com/example/lost/LocationAvailabilityActivity.java, lost-sample/src/main/java/com/example/lost/LocationListenerActivity.java, lost-sample/src/main/java/com/example/lost/LostApiClientActivity.java, lost-sample/src/main/java/com/example/lost/MultipleLocationListenerMultipleClientsActivity.java, lost-sample/src/main/java/com/example/lost/MultipleLocationListenerSingleClientActivity.java, lost-sample/src/main/res/layout/activity_geofencing.xml, lost/src/main/java/com/mapzen/android/lost/api/LostApiClient.java, lost/src/main/java/com/mapzen/android/lost/internal/GeofencingApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/LostApiClientImpl.java
This PR adds `LostApiClient#unregisterConnectionCallbacks` so that developers can prevent leaking resources when adding callbacks in `LostApiClient.Builder.addConnectionCallbacks`
It also updates the sample app examples to use cleanup registered callbacks.
Future work will add `LostApiClient#registerConnectionCallbacks` to allow adding callbacks after the client has been created
Closes #206
=> Unregister callbacks

circle.yml
Our `gh-pages` branch is just documentation which means no tests get run but circle kicks off a build when changes are pushed to this branch. We recently updated documentation deployment so that every `master` build would refresh the docs and therefore push to `gh-pages`. These `gh-pages` builds are noisy (they send a "No tests: mapzen/lost on gh-pages" email) and unnecessary. This PR updates circle to not run builds for changes to the `gh-pages` branch 
https://circleci.com/docs/2.0/configuration-reference/#branches
=> Ignore gh-pages on Circle

README.md, docs/upgrade-2x-3.md
Adds upgrading from 2.x doc to address potential confusion
Closes #225
=> add upgrading 2x - 3 doc

lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceDelegate.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationServiceCallbackManager.java
This is the [first step](https://github.com/mapzen/lost/issues/229) towards improving and standardizing exception handling in Lost. Currently we catch and re-throw `RuntimeExceptions` thrown when interacting with the service, a hard stance for a library to take. To work towards giving developers the chance to handle recovering from these cases, this PR updates Lost to silently ignore `RemoteExceptions`. Future work will provide complete APIs to allow developers to handle recovering from these states as they see fit. It will potentially migrate [existing silent failures](https://github.com/mapzen/lost/blob/master/lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java#L144-L166) to use these new APIs.
Closes #218, #223
=> Log Exceptions

lost-sample/src/main/AndroidManifest.xml, lost-sample/src/main/java/com/example/lost/ListenerService.java, lost-sample/src/main/java/com/example/lost/MultipleProcessesActivity.java, lost-sample/src/main/java/com/example/lost/PendingIntentActivity.java, lost-sample/src/main/java/com/example/lost/SamplesList.java, lost-sample/src/main/res/values/strings.xml, lost/src/main/aidl/com/mapzen/android/lost/internal/IFusedLocationProviderCallback.aidl, lost/src/main/aidl/com/mapzen/android/lost/internal/IFusedLocationProviderService.aidl, lost/src/main/java/com/mapzen/android/lost/api/LocationRequest.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderService.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceDelegate.java, lost/src/main/java/com/mapzen/android/lost/internal/LocationEngine.java, lost/src/main/java/com/mapzen/android/lost/internal/PidReader.java, lost/src/test/java/com/mapzen/android/lost/api/LocationRequestTest.java, lost/src/test/java/com/mapzen/android/lost/api/LocationSettingsRequestTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderServiceDelegateTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LocationSettingsResultRequestTest.java, lost/src/test/java/com/mapzen/android/lost/internal/LostRequestManagerTests.java, lost/src/test/java/com/mapzen/android/lost/internal/TestPidReader.java, lost/src/test/java/com/mapzen/android/lost/internal/TestServiceStub.java
Updates the service delegate to allow multiple remote callbacks (previously only one was allowed).
These changes update the service delegate to hold a `Map` of `IFusedLocationProviderCallback`s keyed off of the process id they were created in. This PR also updates `LocationRequest` to include a `pid` property to allow multiple processes to request & remove location updates for the same location parameters (interval, priority, etc) without effecting the other processes. Finally, it adds an example to the sample app to demonstrate using Lost in a `Service` running in its own process as well as an `Activity` running within the main process.
Closes #228
=> Multiple Processes

lost/src/main/java/com/mapzen/android/lost/api/LocationServices.java, lost/src/main/java/com/mapzen/android/lost/internal/ClientManager.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java, lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationServiceCallbackManager.java, lost/src/main/java/com/mapzen/android/lost/internal/LostClientManager.java, lost/src/main/java/com/mapzen/android/lost/internal/ReportedChanges.java, lost/src/test/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImplTest.java, lost/src/test/java/com/mapzen/android/lost/internal/ReportedChangesTest.java
This fixes a bug which prevented initial location updates from consistently being sent when clients re-connect to Lost.
The `ClientManager` is a shared singleton used by `LostApiClient` and `FusedLocationProviderApi` to report location updates. When the service is started for the first  time, the `ClientManager` doesn't have any `ReportedChanges` and always sends the first location received to registered listeners. When the service is stopped and restarted quickly, the last known location reported by the service may not have changed and because the `ClientManager`'s `ReportedChanges` were not cleared, the location reported might not be sent to registered listeners (because it was compared to "stale" `ReportedChanges`). This PR adds code to "shutdown" the `ClientManager` when the service …
=> Shutdown Client Manager

circle.yml
Limits jvm heap to prevent build failures on circle
https://circleci.com/docs/1.0/oom/#out-of-memory-errors-in-android-builds
=> Improve Circle builds
